import type { Metadata } from "next";
import s from "./download.module.css";
export const metadata: Metadata = { title: "Download Crew.Ship", description: "Your next Minecraft server starts here. Download Crew.Ship for Windows and host on your own computer.", icons: { icon: "/favicon.ico" } };
const releases = "https://github.com/VirtualFox3/Crew.Ship/releases";
export default function DownloadPage() {
  return <main className={s.page}>
    <header className={s.header}><a href="/" className={s.brand}><img src="/brand/ship.svg" width="48" height="48" alt="" /><span>Crew.Ship</span></a><nav aria-label="Main navigation"><a href="#aboard">How it works</a><a href={releases}>Release notes</a><a href="#download" className={s.navDownload}>Get the app</a></nav></header>
    <section className={s.hero} id="download"><div className={s.intro}><p className={s.kicker}><span /> Free desktop Minecraft hosting</p><h1>Your next<br />world starts<br />here.</h1><p className={s.description}>A little ship. A whole world of possibilities. Run a Minecraft server on your PC and bring your friends aboard.</p><a className={s.download} href="/download/windows">↓ Download for Windows</a><p className={s.meta}>Windows 10 / 11 · 64-bit · Free to use</p><a className={s.secondary} href="/download/windows?format=msi">Need the MSI installer?</a></div>
    </section>
    <div className={s.engines}><span>Pick your server software</span><p>Vanilla <b>·</b> Paper <b>·</b> Purpur <b>·</b> Fabric <b>·</b> Forge <b>·</b> NeoForge</p></div>
    <section className={s.aboard} id="aboard"><div><p className={s.kicker}>Welcome aboard</p><h2>From download<br />to game night.</h2><p>Keep your PC on while you host. Your server runs on its memory and saves its world to your drive.</p></div><ol><li><span>1</span><div><h3>Install Crew.Ship</h3><p>Download the Windows installer and open the app.</p></div></li><li><span>2</span><div><h3>Make it your world</h3><p>Choose your Minecraft version and software. Add compatible mods or plugins from Marketplace.</p></div></li><li><span>3</span><div><h3>Bring your friends</h3><p>Use the LAN address for local players. Connect the bundled playit.gg agent to your Playit account for internet players.</p></div></li></ol></section>
    <section className={s.details}><h2>Before you set sail</h2><details><summary>Where does my server run?</summary><p>On your computer. Crew.Ship manages the server locally; your PC needs to stay awake while players are connected. Java is required for Java Edition servers.</p></details><details><summary>Which Minecraft clients can connect?</summary><p>These servers are for Minecraft Java Edition. Use a compatible game version. Modded servers may also require matching mods and loaders on each player's client.</p></details><details><summary>Where do downloads come from?</summary><p>The download button selects the newest published Windows installer from the official VirtualFox3/Crew.Ship GitHub repository. If GitHub cannot return it, you will be sent to the release list.</p></details><details><summary>Is the Windows installer signed?</summary><p>Current Crew.Ship releases are unsigned and Windows may show a publisher warning. Download only from this page or the official repository. Code signing is separate from the bundled Playit agent's signature.</p></details></section>
    <footer className={s.footer}><a className={s.brand} href="/"><img src="/brand/ship.svg" width="38" height="38" alt="" />Crew.Ship</a><p>An independent project. Not affiliated with Mojang or Microsoft.</p><a href="https://github.com/VirtualFox3/Crew.Ship">Source on GitHub</a></footer>
  </main>;
}
