import Link from "next/link";
import { getUser } from "@/lib/supabase/server";
import { isConfigured } from "@/lib/env";

export const dynamic = "force-dynamic";

export default async function LandingPage() {
  const user = isConfigured() ? await getUser() : null;
  return <main className="min-h-screen bg-[#f0f1f3] text-[#1c2029]">
    <header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><PixelShip compact /><b className="font-mono text-sm tracking-[.14em]">CREW.SHIP</b></Link><nav className="hidden gap-7 font-mono text-[11px] font-bold tracking-[.08em] text-[#596173] md:flex"><a href="#how">HOW IT WORKS</a><a href="#features">FEATURES</a><Link href="/download">DOWNLOAD</Link></nav><div className="flex items-center gap-4 font-mono text-[11px] font-bold"><Link href={user ? "/dashboard" : "/login"}>LOG IN</Link><Link href="/download" className="bg-[#2d61dc] px-4 py-3 text-white shadow-[4px_4px_0_#dc5367]">GET THE APP</Link></div></header>

    <section className="relative mx-auto grid max-w-7xl gap-10 overflow-hidden px-5 pb-14 pt-9 sm:px-8 lg:grid-cols-[1.07fr_.93fr] lg:items-center lg:pb-24 lg:pt-16"><div className="absolute right-[-100px] top-[-150px] size-[500px] border-[42px] border-[#2d61dc]/10" /><div className="relative"><p className="inline-flex items-center gap-3 border border-[#c7ccd6] bg-white px-3 py-2 font-mono text-[10px] font-bold tracking-[.12em]"><span className="size-2 bg-[#51d092] shadow-[0_0_0_3px_#dff7eb]" />MINECRAFT, ON YOUR COMPUTER</p><h1 className="mt-7 max-w-3xl font-mono text-5xl font-black leading-[.87] tracking-[-.09em] sm:text-7xl lg:text-[88px]">HOST IT.<br />OWN IT.<br /><span className="text-[#2d61dc]">CREW IT.</span></h1><p className="mt-7 max-w-xl text-base leading-relaxed text-[#5b6576]">Crew.Ship is a native Minecraft host for the PC you already have. Create a world, install add-ons, share access with your crew, and keep every file right where it belongs.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/download" className="bg-[#2d61dc] px-6 py-4 font-mono text-sm font-black text-white shadow-[7px_7px_0_#dc5367] transition-transform hover:-translate-y-1">DOWNLOAD FOR WINDOWS</Link><Link href={user ? "/dashboard" : "/login"} className="border border-[#1c2029] bg-white px-5 py-3.5 font-mono text-sm font-bold">OPEN WEB PANEL</Link></div></div><div className="relative mx-auto w-full max-w-[480px] border-2 border-[#1c2029] bg-[#22252d] p-5 shadow-[12px_12px_0_#dc5367]"><div className="flex items-center justify-between border-b border-white/15 pb-4 font-mono text-[10px] text-[#cfd8e9]"><span>CREW.SHIP DESKTOP</span><span className="text-[#65db9f]">● ONLINE</span></div><div className="grid place-items-center py-10"><PixelShip /></div><div className="grid grid-cols-3 border border-white/10 font-mono"><Fact value="LOCAL" label="HOST" /><Fact value="6" label="SOFTWARES" /><Fact value="FREE" label="TO USE" /></div></div></section>

    <section id="how" className="border-y border-[#c7ccd6] bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-[#c7ccd6] px-5 sm:px-8 md:grid-cols-3 md:divide-x md:divide-y-0"><Step number="01" title="Create" text="Pick Vanilla, Paper, Purpur, Fabric, Forge, or NeoForge. Crew.Ship gets the official build." /><Step number="02" title="Run locally" text="Your world uses your computer, your storage, and your own Minecraft server folder." /><Step number="03" title="Share" text="Invite admins by Crew.Ship username or a single-use link. Use playit.gg for a public address." /></div></section>
    <section id="features" className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#2d61dc]">BUILT FOR A LOCAL HOST</p><h2 className="mt-3 max-w-3xl font-mono text-3xl font-black tracking-[-.07em] sm:text-5xl">Your server has a real control room.</h2><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Feature title="Server options" text="Slots, whitelist, difficulty, keep inventory, resource packs, and more." /><Feature title="Marketplace" text="One-click compatible mods and plugins through Modrinth." /><Feature title="Files & worlds" text="Open local folders whenever you need full control of your data." /><Feature title="Console & crew" text="Live console, logs, player controls, backups, and secure access invites." /></div></section>
    <footer className="bg-[#1c2029] px-5 py-8 text-[#dfe7f5] sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 font-mono text-[10px] tracking-[.11em]"><span>CREW.SHIP · LOCAL MINECRAFT HOSTING</span><a href="https://github.com/VirtualFox3/Crew.Ship" className="text-[#9dbaff]">GITHUB ↗</a></div></footer>
  </main>;
}

function PixelShip({ compact = false }: { compact?: boolean }) { const size = compact ? "scale-[.48] origin-left" : "scale-100"; return <span aria-hidden="true" className={`relative block h-24 w-28 ${size}`}><i className="absolute bottom-2 left-3 h-3 w-20 bg-[#f4f5f7] shadow-[6px_6px_0_#2d61dc,12px_6px_0_#f4f5f7,18px_6px_0_#f4f5f7,24px_6px_0_#f4f5f7,30px_6px_0_#f4f5f7,36px_6px_0_#f4f5f7,42px_6px_0_#f4f5f7]" /><i className="absolute bottom-0 left-8 h-1.5 w-14 bg-[#2d61dc]" /><i className="absolute left-[51px] top-2 h-16 w-2 bg-[#f4f5f7]" /><i className="absolute left-[59px] top-3 h-8 w-10 bg-[#dc5367]" /><i className="absolute left-4 top-7 h-10 w-9 bg-[#2d61dc]" /><i className="absolute left-7 top-10 h-3 w-3 bg-[#d9e7ff]" /></span>; }
function Fact({ value, label }: { value: string; label: string }) { return <div className="p-4"><b className="text-lg text-white">{value}</b><p className="mt-1 text-[8px] tracking-[.12em] text-[#a1adbe]">{label}</p></div>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <article className="px-0 py-7 md:px-7"><span className="font-mono text-[10px] font-bold text-[#dc5367]">{number}</span><h2 className="mt-3 font-mono text-xl font-black tracking-[-.06em]">{title}</h2><p className="mt-3 text-sm leading-relaxed text-[#626d7e]">{text}</p></article>; }
function Feature({ title, text }: { title: string; text: string }) { return <article className="border border-[#c7ccd6] bg-white p-5 shadow-[4px_4px_0_#d4d8e1]"><h3 className="font-mono text-base font-black tracking-[-.04em]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#626d7e]">{text}</p></article>; }
